"""The automatic dashboard: measures, breakdowns and trends built without the model.

Every number here comes from SQL generated by these rules, run through the same
guard as the model's SQL. A measure the customer has defined in metrics.toml is
used exactly as defined, so the dashboard and the chat can never disagree on
what "revenue" means.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

import engine


_AGGREGATE = re.compile(r"\b(sum|avg|count|min|max|median)\s*\(", re.I)


def q(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


@dataclass
class Measure:
    label: str           # becomes the result column name, so it drives formatting
    expression: str      # an aggregate over the fact table's own columns
    meaning: str = ""    # set when it is an agreed definition


@dataclass
class Dimension:
    label: str
    table: str
    column: str
    on: tuple[str, str] | None = None   # (fact column, dimension column) when joined


def measures(table, metrics: list[dict]) -> list[Measure]:
    out = [Measure(m["name"], m["expression"], m["meaning"])
           for m in metrics
           # a definition like fiscal_year is a row-level expression, not a measure
           if m["table"] == table.name and _AGGREGATE.search(m["expression"])]
    for c in table.columns:
        numeric = c.dtype in ("DECIMAL", "INTEGER")
        if numeric and c.distinct > 2 and not engine._ID_LIKE.search(c.name):
            out.append(Measure(f"total_{c.name}", f"SUM({q(c.name)})"))
    out.append(Measure("row_count", "COUNT(*)"))
    return out


def dimensions(table, tables: list, joins: list[dict]) -> list[Dimension]:
    """Category columns of this table, plus those reachable through one detected join."""
    by_name = {t.name: t for t in tables}
    out = [Dimension(c.name, table.name, c.name)
           for c in table.columns if c.values and c.dtype == "TEXT"]
    taken = {d.label for d in out}
    for j in joins:
        (lt, lc), (rt, rc) = j["left"].split(".", 1), j["right"].split(".", 1)
        if lt == table.name:
            other, fact_col, dim_col = rt, lc, rc
        elif rt == table.name:
            other, fact_col, dim_col = lt, rc, lc
        else:
            continue
        for c in by_name[other].columns:
            if c.values and c.dtype == "TEXT" and c.name != dim_col:
                label = c.name if c.name not in taken else f"{other}_{c.name}"
                taken.add(label)
                out.append(Dimension(label, other, c.name, (fact_col, dim_col)))
    return out


def dates(table) -> list[str]:
    return [c.name for c in table.columns if c.dtype == "DATE"]


def fact_tables(tables: list, metrics: list[dict]) -> list:
    """Tables worth a dashboard, the one with a defined metric or the most rows first."""
    defined = {m["table"] for m in metrics}
    worth = [t for t in tables if len(measures(t, metrics)) > 1 or dates(t)]
    return sorted(worth, key=lambda t: (t.name not in defined, -t.rows))


def compact(v, money: bool = False) -> str:
    """A number short enough for a stat tile: $1.96M, 62.7K, 12.50. Never truncated."""
    if v is None or v != v:  # None or NaN
        return "—"
    sign, v = ("-" if v < 0 else ""), abs(float(v))
    # (show from, divide by, suffix): thousands only abbreviate from 10K up
    unit = next(((d, u) for at, d, u in ((1e9, 1e9, "B"), (1e6, 1e6, "M"), (1e4, 1e3, "K"))
                 if v >= at), None)
    if unit:
        num = f"{v / unit[0]:,.3g}{unit[1]}"
    else:
        num = f"{v:,.0f}" if v >= 100 or v == int(v) else f"{v:,.2f}"
    return sign + ("$" if money else "") + num


def kpi_sql(table, m: Measure) -> str:
    return f"SELECT {m.expression} AS {q(m.label)}, COUNT(*) AS row_count FROM {q(table.name)}"


def trend_sql(table, m: Measure, date_col: str) -> str:
    return (f"SELECT date_trunc('month', {q(date_col)}) AS month, {m.expression} AS {q(m.label)} "
            f"FROM {q(table.name)} WHERE {q(date_col)} IS NOT NULL GROUP BY 1 ORDER BY 1")


def breakdown_sql(table, m: Measure, d: Dimension) -> str:
    # Joined columns arrive as one extra column on the fact rows, so a defined
    # metric's bare column names still refer to the fact table and nothing else.
    if d.on is None:
        base = f"SELECT *, {q(d.column)} AS __dim FROM {q(table.name)}"
    else:
        fact_col, dim_col = d.on
        base = (f"SELECT f.*, d.{q(d.column)} AS __dim FROM {q(table.name)} f "
                f"LEFT JOIN {q(d.table)} d ON f.{q(fact_col)} = d.{q(dim_col)}")
    return (f"WITH base AS ({base}) SELECT __dim AS {q(d.label)}, {m.expression} AS {q(m.label)} "
            f"FROM base GROUP BY 1 ORDER BY 2 DESC NULLS LAST")
